# Generated by Django 3.1.5 on 2024-10-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20241026_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
