# Generated by Django 3.1.5 on 2024-10-26 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_auto_20241026_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('assigned_to', models.CharField(max_length=256, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.evenimente')),
            ],
        ),
        migrations.CreateModel(
            name='CompleteTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.CharField(max_length=256, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.task')),
            ],
        ),
    ]
