# Generated by Django 3.1.5 on 2024-10-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_completetask_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completetask',
            name='task',
        ),
    ]
