# Generated by Django 3.1.5 on 2024-10-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_auto_20241026_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenimente',
            name='number_of_people',
            field=models.IntegerField(null=True),
        ),
    ]
